version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./feedback-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
